modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="creeperknight"
version="${version}"
displayName="Creeper Knight / 苦力怕骑士"
authors="Snowflake"
description='''Creeper jockeys, player-controlled creeper mounts with charge explosions, a friendship scepter and synchronized in-game settings.'''
[[dependencies.creeperknight]]
modId="forge"
mandatory=true
versionRange="[47.2.0,48)"
ordering="NONE"
side="BOTH"
[[dependencies.creeperknight]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
